[package]
name = "uefi_stub"
version = "0.1.0"
authors = ["Han Mertens <hanmertens@outlook.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
log = "0.4"
uefi = "0.9"
x86_64 = "0.14"
xmas-elf = "0.7"
