[package]
name = "common"
version = "0.1.0"
authors = ["Han Mertens <hanmertens@outlook.com>"]
edition = "2018"

[dependencies]
uefi = "0.8"
spin = { version = "0.9", default-features = false, features = ["spin_mutex"] }
uart_16550 = "0.2"
x86_64 = "0.13"
